### ISSUE TITLE
dist folder with d.ts files

### ISSUE THREAD

**Issue by lorypelli** [PurGPT/purgpt.js#2]
this will guaranteen typescript support, do it pls

**Comment by Tolga1452** [comment]
if you can, can you please open a pull request? this would be helpful

**Comment by lorypelli** [comment]
> if you can, can you please open a pull request? this would be helpful

https://github.com/PurGPT/purgpt.js/pull/3

**Comment by Tolga1452** [comment]
Thank you!

**Comment by Tolga1452** [comment]
is it ok now?

**Comment by lorypelli** [comment]
> is it ok now?

It didn't worked
Try to add types entry in `package.json`

**Comment by lorypelli** [comment]
![image](https://github.com/PurGPT/purgpt.js/assets/87276663/e476cf3e-cfef-4e47-9ea6-c6f6db67b373)
still no typescript support

**Comment by Tolga1452** [comment]
> ![image](https://user-images.githubusercontent.com/87276663/258587278-e476cf3e-cfef-4e47-9ea6-c6f6db67b373.png) still no typescript support

i don't know how to do it 😔

**Comment by lorypelli** [comment]
> > ![image](https://user-images.githubusercontent.com/87276663/258587278-e476cf3e-cfef-4e47-9ea6-c6f6db67b373.png) still no typescript support
> 
> i don't know how to do it 😔

As example: my npm package
https://github.com/lorypelli/serverless_bots_addons

**Comment by Tolga1452** [comment]
i did
![image](https://github.com/PurGPT/purgpt.js/assets/68483180/9ad724ee-fc6b-4483-a538-eec82508dce4)
