### ISSUE TITLE
Add back dist folder

### ISSUE THREAD

**Issue by lorypelli** [PurGPT/purgpt.js#4]
You removed it but without it we can't use the package

**Comment by lorypelli** [comment]
When you removed `outDir` property from `tsconfig`

**Comment by Tolga1452** [comment]
> When you removed `outDir` property from `tsconfig`

i removed it because they were in `src` folder, i think the folder doesn't matter

**Comment by Tolga1452** [comment]
![image](https://github.com/PurGPT/purgpt.js/assets/68483180/bec59eb9-b3ab-45d0-a7ad-c0d04897c7f4)

**Comment by lorypelli** [comment]
> > When you removed `outDir` property from `tsconfig`
> 
> i removed it because they were in `src` folder, i think the folder doesn't matter

That folder is outDir folder by tsc command, you shouldn't delete it

**Comment by lorypelli** [comment]
for you it works maybe because you are taking types from src folder, but you should take them from dist folder (in package.json I mean)

**Comment by lorypelli** [comment]
ehm...I'm testing and it seems to work fine

**Comment by lorypelli** [comment]
You should keep it as it is
